title: iâ¤code.cf
author: acimanx.github.io
description: >
  Hi and welcome on my amazing github frontpage!
github_username:  acimanx
show_excerpts: false
theme: minima
header_pages:
  - about.md
disqus:
    shortname: acimanx-github-io
